/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Funcionario;

import dao.FuncionarioDAO;
import dao.GerenteDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.Veiculo;

/**
 *
 * @author luis_
 */
public class Catalogo extends javax.swing.JPanel {

     public String hora;
    public Catalogo() {
        initComponents();
        Veiculo_tabela();
    }
 public void Veiculo_tabela(){
    DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
    model.setNumRows(0);
    GerenteDAO dao = new GerenteDAO();
    
    for(Veiculo v: dao.ListarVeiculos()){
        model.addRow(new Object[]{
            v.getId(),
            v.getFoto(),   
            v.getModelo(),
            v.getFabricante(),
            v.getAno(),
            v.getCor(),
            v.getPreco(),
            v.getNumChassi(),
            v.getDescricao(),
            v.getQuilometragem()
        });
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Geral = new javax.swing.JPanel();
        esquerd_panel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        pag2 = new javax.swing.JPanel();
        Tabela_scroll = new javax.swing.JScrollPane();
        Tabela = new rojerusan.RSTableMetro();
        enviar1 = new javax.swing.JButton();
        limpar1 = new javax.swing.JButton();

        Geral.setBackground(new java.awt.Color(0, 0, 0));
        Geral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esquerd_panel.setBackground(new java.awt.Color(255, 0, 0));
        esquerd_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                esquerd_panelMouseEntered(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Catálogo");
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tituloMouseExited(evt);
            }
        });

        javax.swing.GroupLayout esquerd_panelLayout = new javax.swing.GroupLayout(esquerd_panel);
        esquerd_panel.setLayout(esquerd_panelLayout);
        esquerd_panelLayout.setHorizontalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esquerd_panelLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(titulo)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        esquerd_panelLayout.setVerticalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esquerd_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Geral.add(esquerd_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        Principal.setBackground(new java.awt.Color(0, 0, 0));
        Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrincipalMouseEntered(evt);
            }
        });
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pag2.setBackground(new java.awt.Color(0, 0, 0));
        pag2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Principal.add(pag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 610, 710, 630));

        Tabela_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Tabela_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Tabela_scroll.setPreferredSize(new java.awt.Dimension(620, 300));
        Tabela_scroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tabela_scrollMouseEntered(evt);
            }
        });

        Tabela.setBackground(new java.awt.Color(0, 0, 0));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Imagem", "Modelo", "Fabricante", "Ano", "Cor", "Preço", "Nº Chassi", "Descrição", "Quilometragem"
            }
        ));
        Tabela.setColorBackgoundHead(new java.awt.Color(0, 255, 255));
        Tabela.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabela.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabela.setColorSelBackgound(new java.awt.Color(0, 255, 255));
        Tabela.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        Tabela.setFuenteFilas(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tabela.setGridColor(new java.awt.Color(230, 230, 230));
        Tabela.setOpaque(false);
        Tabela.setRowHeight(20);
        Tabela.setRowMargin(0);
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabelaMouseEntered(evt);
            }
        });
        Tabela_scroll.setViewportView(Tabela);

        Principal.add(Tabela_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 660, 300));

        enviar1.setBackground(new java.awt.Color(255, 0, 0));
        enviar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enviar1.setForeground(new java.awt.Color(255, 255, 255));
        enviar1.setText("Adicionar ao carrinho");
        enviar1.setBorder(null);
        enviar1.setContentAreaFilled(false);
        enviar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar1.setOpaque(true);
        enviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar1ActionPerformed(evt);
            }
        });
        Principal.add(enviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 120, 40));

        limpar1.setBackground(new java.awt.Color(255, 0, 0));
        limpar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar1.setForeground(new java.awt.Color(255, 255, 255));
        limpar1.setText("Limpar");
        limpar1.setBorder(null);
        limpar1.setContentAreaFilled(false);
        limpar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpar1.setOpaque(true);
        limpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar1ActionPerformed(evt);
            }
        });
        Principal.add(limpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 120, 40));

        Geral.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Geral, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseClicked

    private void tituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseEntered

    private void tituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseExited

    private void esquerd_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esquerd_panelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_esquerd_panelMouseEntered

    private void PrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMouseEntered
                                 int position = esquerd_panel.getY();
             Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel); 
               if(position != 0){
                      esquerd_panel.setVisible(false);
                            titulo.setVisible(false);}
    }//GEN-LAST:event_PrincipalMouseEntered

    private void enviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar1ActionPerformed
        int dialogo=JOptionPane.showConfirmDialog(null,"Tem certeza?");
        if(dialogo==0){
        String id= Tabela.getValueAt(Tabela.getSelectedRow(),0).toString();
  String preco= Tabela.getValueAt( Tabela.getSelectedRow(),6).toString();
  String modelo= Tabela.getValueAt(Tabela.getSelectedRow(),2).toString();
  String nome= Prin_funcionario.login_func.getText();
              Date data= new Date();
            SimpleDateFormat form= new SimpleDateFormat("dd/MM/yyy");
        System.out.println("id: "+id);
        System.out.println("preco: "+preco);
        System.out.println("modelo: "+modelo);
     Veiculo vei= new  Veiculo();
            vei.setModelo(modelo);
            //vei.setFoto(Tabela.getValueAt(Tabela.getSelectedRow(),4));
            vei.setPreco(Float.parseFloat(preco));
             //vei.setId(vei.getId()));
             vei.setNome(nome);
             vei.setDatanasc(form.format(data));
            FuncionarioDAO dao= new FuncionarioDAO();
            dao.AdicionarCarrinhoAoCarrinho(vei);
        }else{JOptionPane.showMessageDialog(null,"O veiculo não foi adicionado!");}
    }//GEN-LAST:event_enviar1ActionPerformed

    private void limpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar1ActionPerformed
        
    }//GEN-LAST:event_limpar1ActionPerformed

    private void TabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseEntered
                int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titulo.setVisible(false);}
    }//GEN-LAST:event_TabelaMouseEntered

    private void Tabela_scrollMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_scrollMouseEntered
                int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titulo.setVisible(false);}
    }//GEN-LAST:event_Tabela_scrollMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Geral;
    private javax.swing.JPanel Principal;
    private rojerusan.RSTableMetro Tabela;
    private javax.swing.JScrollPane Tabela_scroll;
    private javax.swing.JButton enviar1;
    private javax.swing.JPanel esquerd_panel;
    private javax.swing.JButton limpar1;
    private javax.swing.JPanel pag2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables


}
