/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Funcionario;

import dao.FuncionarioDAO;
import dao.GerenteDAO;
import dao.VeiculoDAO;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;
import model.Veiculo;

/**
 *
 * @author Vanêssa Gomes
 */
public class Tabela extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Tabela() {
        initComponents();
        Carrinho_tabela();
    }
      public void Carrinho_tabela(){
    DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
    model.setNumRows(0);
          FuncionarioDAO dao = new FuncionarioDAO();
    
    for(Veiculo v: dao.ListarCarrinho()){
        model.addRow(new Object[]{
            v.getId(),
            v.getFoto(),   
            v.getPreco(),
            v.getNome(),
            v.getModelo(),
            v.getDatanasc(),
        });
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tools = new javax.swing.JPopupMenu();
        Apagar = new javax.swing.JMenuItem();
        Ver_relatorio = new javax.swing.JMenuItem();
        rpdf = new javax.swing.JMenuItem();
        Alterar = new javax.swing.JMenuItem();
        esquerd_panel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        pag2 = new javax.swing.JPanel();
        Tabela_scroll = new javax.swing.JScrollPane();
        Tabela = new rojerusan.RSTableMetro();
        enviar1 = new javax.swing.JButton();
        limpar1 = new javax.swing.JButton();

        Tools.setBackground(new java.awt.Color(255, 255, 255));
        Tools.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tools.setForeground(new java.awt.Color(0, 255, 255));
        Tools.setOpaque(false);

        Apagar.setBackground(new java.awt.Color(255, 255, 255));
        Apagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Apagar.setForeground(new java.awt.Color(0, 255, 255));
        Apagar.setText("Apagar");
        Apagar.setContentAreaFilled(false);
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });
        Tools.add(Apagar);

        Ver_relatorio.setBackground(new java.awt.Color(255, 255, 255));
        Ver_relatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ver_relatorio.setForeground(new java.awt.Color(0, 255, 255));
        Ver_relatorio.setText("Exibir relatório");
        Ver_relatorio.setContentAreaFilled(false);
        Ver_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_relatorioActionPerformed(evt);
            }
        });
        Tools.add(Ver_relatorio);

        rpdf.setBackground(new java.awt.Color(255, 255, 255));
        rpdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rpdf.setForeground(new java.awt.Color(0, 255, 255));
        rpdf.setText("Relatório em PDF");
        rpdf.setContentAreaFilled(false);
        rpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpdfActionPerformed(evt);
            }
        });
        Tools.add(rpdf);

        Alterar.setBackground(new java.awt.Color(255, 255, 255));
        Alterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alterar.setForeground(new java.awt.Color(0, 255, 255));
        Alterar.setText("Alterar dados");
        Alterar.setContentAreaFilled(false);
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        Tools.add(Alterar);

        setLayout(null);

        esquerd_panel.setBackground(new java.awt.Color(255, 0, 0));
        esquerd_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                esquerd_panelMouseEntered(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Carrinho");
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tituloMouseExited(evt);
            }
        });

        javax.swing.GroupLayout esquerd_panelLayout = new javax.swing.GroupLayout(esquerd_panel);
        esquerd_panel.setLayout(esquerd_panelLayout);
        esquerd_panelLayout.setHorizontalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esquerd_panelLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(titulo)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        esquerd_panelLayout.setVerticalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esquerd_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(esquerd_panel);
        esquerd_panel.setBounds(0, 0, 690, 60);

        Principal.setBackground(new java.awt.Color(0, 0, 0));
        Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrincipalMouseEntered(evt);
            }
        });
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pag2.setBackground(new java.awt.Color(0, 0, 0));
        pag2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Principal.add(pag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 610, 710, 630));

        Tabela_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Tabela_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Tabela_scroll.setPreferredSize(new java.awt.Dimension(620, 300));
        Tabela_scroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tabela_scrollMouseEntered(evt);
            }
        });

        Tabela.setBackground(new java.awt.Color(0, 0, 0));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº pedido", "Imagem", "Preço", "Vendedor", "Modelo", "Data da adição ao carrinho"
            }
        ));
        Tabela.setColorBackgoundHead(new java.awt.Color(0, 255, 255));
        Tabela.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabela.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabela.setColorSelBackgound(new java.awt.Color(0, 255, 255));
        Tabela.setComponentPopupMenu(Tools);
        Tabela.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        Tabela.setFuenteFilas(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tabela.setGridColor(new java.awt.Color(230, 230, 230));
        Tabela.setOpaque(false);
        Tabela.setRowHeight(20);
        Tabela.setRowMargin(0);
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabelaMouseEntered(evt);
            }
        });
        Tabela_scroll.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(2).setResizable(false);
        }

        Principal.add(Tabela_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 660, 300));

        enviar1.setBackground(new java.awt.Color(255, 0, 0));
        enviar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enviar1.setForeground(new java.awt.Color(255, 255, 255));
        enviar1.setText("Finalizar Compra");
        enviar1.setBorder(null);
        enviar1.setContentAreaFilled(false);
        enviar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar1.setOpaque(true);
        enviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar1ActionPerformed(evt);
            }
        });
        Principal.add(enviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 200, 40));

        limpar1.setBackground(new java.awt.Color(255, 0, 0));
        limpar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar1.setForeground(new java.awt.Color(255, 255, 255));
        limpar1.setText("Limpar");
        limpar1.setBorder(null);
        limpar1.setContentAreaFilled(false);
        limpar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpar1.setOpaque(true);
        limpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar1ActionPerformed(evt);
            }
        });
        Principal.add(limpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 120, 40));

        add(Principal);
        Principal.setBounds(0, 0, 690, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void enviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar1ActionPerformed

     
    }//GEN-LAST:event_enviar1ActionPerformed

    private void limpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar1ActionPerformed
       
    }//GEN-LAST:event_limpar1ActionPerformed

    private void PrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMouseEntered
        int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titulo.setVisible(false);}
    }//GEN-LAST:event_PrincipalMouseEntered

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseClicked

    private void tituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseEntered

    private void tituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseExited

    private void esquerd_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esquerd_panelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_esquerd_panelMouseEntered

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
    FuncionarioDAO dao= new FuncionarioDAO();    
      if(Tabela.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione uma linha", " Vilet's Muscles Informa...", JOptionPane.ERROR_MESSAGE);
        } else{
           Veiculo vv= new Veiculo();
            int id = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
            vv.setId(id);
            dao.removerDoCarrinho(vv);
          Carrinho_tabela();
      }
      
    }//GEN-LAST:event_ApagarActionPerformed

    private void Ver_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_relatorioActionPerformed
       
    }//GEN-LAST:event_Ver_relatorioActionPerformed

    private void rpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpdfActionPerformed

    }//GEN-LAST:event_rpdfActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed


    }//GEN-LAST:event_AlterarActionPerformed

    private void TabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseEntered
                int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titulo.setVisible(false);}
    }//GEN-LAST:event_TabelaMouseEntered

    private void Tabela_scrollMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_scrollMouseEntered
               int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titulo.setVisible(false);}
    }//GEN-LAST:event_Tabela_scrollMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alterar;
    private javax.swing.JMenuItem Apagar;
    private javax.swing.JPanel Principal;
    public rojerusan.RSTableMetro Tabela;
    private javax.swing.JScrollPane Tabela_scroll;
    private javax.swing.JPopupMenu Tools;
    private javax.swing.JMenuItem Ver_relatorio;
    private javax.swing.JButton enviar1;
    private javax.swing.JPanel esquerd_panel;
    private javax.swing.JButton limpar1;
    private javax.swing.JPanel pag2;
    private javax.swing.JMenuItem rpdf;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

}
