package view.Gerente;

import dao.VeiculoDAO;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Veiculo;

public class Registrar_veiculo extends javax.swing.JPanel {

    public Registrar_veiculo() {
        initComponents();
       
    }
    
    public void limpar(){
        fabricante.setSelectedItem(null);
        imagem.setIcon(null);
        preco.setText(null);
        modelo.setText(null);
        descricao.setText(null);
        chassi.setText(null);
        Ano_carro.setText(null);
        quilometragem.setText(null);
        cor.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        part_2 = new javax.swing.JPanel();
        cadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        quilometragem = new javax.swing.JTextField();
        quilometragem_text = new javax.swing.JLabel();
        cor_text = new javax.swing.JLabel();
        Ano_carro = new javax.swing.JFormattedTextField();
        ano_text = new javax.swing.JLabel();
        chassi = new javax.swing.JTextField();
        N_chassi_text = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        preco_text = new javax.swing.JLabel();
        cor = new javax.swing.JComboBox<String>();
        opcionais_text = new javax.swing.JLabel();
        cambio_check = new javax.swing.JCheckBox();
        trava_check = new javax.swing.JCheckBox();
        arquent_check = new javax.swing.JCheckBox();
        tetosolar_check = new javax.swing.JCheckBox();
        radio_check = new javax.swing.JCheckBox();
        arcond_check = new javax.swing.JCheckBox();
        gps_check = new javax.swing.JCheckBox();
        esquerd_panel = new javax.swing.JPanel();
        titul0 = new javax.swing.JLabel();
        modelo_text = new javax.swing.JLabel();
        fabr_text = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        enviar_img = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        desc_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        proximo = new javax.swing.JButton();
        modelo = new javax.swing.JTextField();
        fabricante = new javax.swing.JComboBox<String>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Principal.setBackground(new java.awt.Color(0, 0, 0));
        Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrincipalMouseEntered(evt);
            }
        });
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        part_2.setBackground(new java.awt.Color(0, 0, 0));
        part_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                part_2MouseEntered(evt);
            }
        });
        part_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastrar.setBackground(new java.awt.Color(0, 255, 255));
        cadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("Enviar");
        cadastrar.setBorder(null);
        cadastrar.setContentAreaFilled(false);
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.setOpaque(true);
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        part_2.add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 120, 40));

        voltar.setBackground(new java.awt.Color(0, 255, 255));
        voltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.setOpaque(true);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        part_2.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 120, 40));

        quilometragem.setBackground(new java.awt.Color(0, 255, 255));
        quilometragem.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        quilometragem.setForeground(new java.awt.Color(255, 0, 0));
        quilometragem.setToolTipText("Insira a quilometragem do carro");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder1.setShadowOpacity(1.0F);
        dropShadowBorder1.setShadowSize(10);
        quilometragem.setBorder(dropShadowBorder1);
        quilometragem.setCaretColor(new java.awt.Color(255, 0, 0));
        quilometragem.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        quilometragem.setOpaque(false);
        part_2.add(quilometragem, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 140, 51));

        quilometragem_text.setBackground(new java.awt.Color(0, 255, 255));
        quilometragem_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        quilometragem_text.setForeground(new java.awt.Color(255, 255, 255));
        quilometragem_text.setText("Quilometragem");
        part_2.add(quilometragem_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        cor_text.setBackground(new java.awt.Color(0, 255, 255));
        cor_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        cor_text.setForeground(new java.awt.Color(255, 255, 255));
        cor_text.setText("Cor");
        part_2.add(cor_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        Ano_carro.setBackground(new java.awt.Color(0, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder2.setShadowOpacity(1.0F);
        dropShadowBorder2.setShadowSize(10);
        Ano_carro.setBorder(dropShadowBorder2);
        Ano_carro.setForeground(new java.awt.Color(255, 0, 0));
        try {
            Ano_carro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Ano_carro.setToolTipText("Insira o ano do carro");
        Ano_carro.setCaretColor(new java.awt.Color(255, 0, 0));
        Ano_carro.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        Ano_carro.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Ano_carro.setOpaque(false);
        part_2.add(Ano_carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 120, 51));

        ano_text.setBackground(new java.awt.Color(0, 255, 255));
        ano_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        ano_text.setForeground(new java.awt.Color(255, 255, 255));
        ano_text.setText("Ano");
        part_2.add(ano_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        chassi.setBackground(new java.awt.Color(0, 255, 255));
        chassi.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        chassi.setForeground(new java.awt.Color(255, 0, 0));
        chassi.setToolTipText("Insira o N° do chassi");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder3.setShadowOpacity(1.0F);
        dropShadowBorder3.setShadowSize(10);
        chassi.setBorder(dropShadowBorder3);
        chassi.setCaretColor(new java.awt.Color(255, 0, 0));
        chassi.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        chassi.setOpaque(false);
        chassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chassiActionPerformed(evt);
            }
        });
        part_2.add(chassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 246, 51));

        N_chassi_text.setBackground(new java.awt.Color(0, 255, 255));
        N_chassi_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        N_chassi_text.setForeground(new java.awt.Color(255, 255, 255));
        N_chassi_text.setText("Numero do Chassi");
        part_2.add(N_chassi_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        preco.setBackground(new java.awt.Color(0, 255, 255));
        preco.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        preco.setForeground(new java.awt.Color(255, 0, 0));
        preco.setToolTipText("Insira o preço do carro");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder4.setShadowOpacity(1.0F);
        dropShadowBorder4.setShadowSize(10);
        preco.setBorder(dropShadowBorder4);
        preco.setCaretColor(new java.awt.Color(255, 0, 0));
        preco.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        preco.setOpaque(false);
        part_2.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 51));

        preco_text.setBackground(new java.awt.Color(0, 255, 255));
        preco_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        preco_text.setForeground(new java.awt.Color(255, 255, 255));
        preco_text.setText("Preço");
        part_2.add(preco_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        cor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preto", "Cinza", "Azul", "Vermelho", "Prata", "Amarelo", "Rosa" }));
        part_2.add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 30));

        opcionais_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        opcionais_text.setForeground(new java.awt.Color(255, 255, 255));
        opcionais_text.setText("Opcionais");
        part_2.add(opcionais_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        cambio_check.setForeground(new java.awt.Color(255, 255, 255));
        cambio_check.setText("Câmbio Automático");
        cambio_check.setBorder(null);
        cambio_check.setOpaque(false);
        cambio_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambio_checkActionPerformed(evt);
            }
        });
        part_2.add(cambio_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        trava_check.setForeground(new java.awt.Color(255, 255, 255));
        trava_check.setText("Trava elétrica");
        trava_check.setBorder(null);
        trava_check.setOpaque(false);
        part_2.add(trava_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        arquent_check.setForeground(new java.awt.Color(255, 255, 255));
        arquent_check.setText("Ar quente");
        arquent_check.setBorder(null);
        arquent_check.setOpaque(false);
        arquent_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquent_checkActionPerformed(evt);
            }
        });
        part_2.add(arquent_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        tetosolar_check.setForeground(new java.awt.Color(255, 255, 255));
        tetosolar_check.setText("Teto Solar");
        tetosolar_check.setBorder(null);
        tetosolar_check.setOpaque(false);
        part_2.add(tetosolar_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        radio_check.setForeground(new java.awt.Color(255, 255, 255));
        radio_check.setText("Rádio");
        radio_check.setBorder(null);
        radio_check.setOpaque(false);
        part_2.add(radio_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        arcond_check.setForeground(new java.awt.Color(255, 255, 255));
        arcond_check.setText("Ar condicionado");
        arcond_check.setBorder(null);
        arcond_check.setOpaque(false);
        part_2.add(arcond_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        gps_check.setForeground(new java.awt.Color(255, 255, 255));
        gps_check.setText("GPS");
        gps_check.setBorder(null);
        gps_check.setOpaque(false);
        part_2.add(gps_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        Principal.add(part_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-680, 0, 680, 600));

        esquerd_panel.setBackground(new java.awt.Color(0, 255, 255));
        esquerd_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                esquerd_panelMouseEntered(evt);
            }
        });

        titul0.setBackground(new java.awt.Color(0, 0, 0));
        titul0.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        titul0.setForeground(new java.awt.Color(255, 255, 255));
        titul0.setText("Cadastro Carro");
        titul0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titul0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titul0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                titul0MouseExited(evt);
            }
        });

        javax.swing.GroupLayout esquerd_panelLayout = new javax.swing.GroupLayout(esquerd_panel);
        esquerd_panel.setLayout(esquerd_panelLayout);
        esquerd_panelLayout.setHorizontalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esquerd_panelLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(titul0)
                .addGap(265, 265, 265))
        );
        esquerd_panelLayout.setVerticalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esquerd_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titul0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Principal.add(esquerd_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        modelo_text.setBackground(new java.awt.Color(0, 255, 255));
        modelo_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        modelo_text.setForeground(new java.awt.Color(255, 255, 255));
        modelo_text.setText("Modelo:");
        Principal.add(modelo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        fabr_text.setBackground(new java.awt.Color(255, 255, 255));
        fabr_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        fabr_text.setForeground(new java.awt.Color(255, 255, 255));
        fabr_text.setText("Fabricante:");
        Principal.add(fabr_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        imagem.setBackground(new java.awt.Color(255, 255, 255));
        imagem.setForeground(new java.awt.Color(255, 255, 255));
        imagem.setOpaque(true);
        Principal.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 150, 150));

        enviar_img.setBackground(new java.awt.Color(0, 255, 255));
        enviar_img.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enviar_img.setForeground(new java.awt.Color(255, 255, 255));
        enviar_img.setText("Selecionar imagem");
        enviar_img.setBorder(null);
        enviar_img.setBorderPainted(false);
        enviar_img.setContentAreaFilled(false);
        enviar_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_img.setOpaque(true);
        enviar_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_imgActionPerformed(evt);
            }
        });
        Principal.add(enviar_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 180, 40));

        limpar.setBackground(new java.awt.Color(0, 255, 255));
        limpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.setBorder(null);
        limpar.setContentAreaFilled(false);
        limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpar.setOpaque(true);
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        Principal.add(limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 120, 40));

        desc_text.setBackground(new java.awt.Color(255, 255, 255));
        desc_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        desc_text.setForeground(new java.awt.Color(255, 255, 255));
        desc_text.setText("Descrição:");
        Principal.add(desc_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        descricao.setColumns(20);
        descricao.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 0, 0));
        descricao.setRows(5);
        descricao.setToolTipText("Descreva o carro");
        jScrollPane1.setViewportView(descricao);

        Principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 220, -1));

        proximo.setBackground(new java.awt.Color(0, 255, 255));
        proximo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        proximo.setForeground(new java.awt.Color(255, 255, 255));
        proximo.setText("Próximo");
        proximo.setBorder(null);
        proximo.setContentAreaFilled(false);
        proximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proximo.setOpaque(true);
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });
        Principal.add(proximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 120, 40));

        modelo.setBackground(new java.awt.Color(0, 255, 255));
        modelo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        modelo.setForeground(new java.awt.Color(255, 0, 0));
        modelo.setToolTipText("Insira o modelo do carro");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder5.setShadowOpacity(1.0F);
        dropShadowBorder5.setShadowSize(10);
        modelo.setBorder(dropShadowBorder5);
        modelo.setCaretColor(new java.awt.Color(255, 0, 0));
        modelo.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        modelo.setOpaque(false);
        Principal.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 246, 51));

        fabricante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hyundai", "Peugeot", "Toyota", "Chevrolet", "Ford", "Nissan", "Volkswagen", "Honda", "Mercedes-Benz", "Renault", "Suzuki", "Mitsubishi", " " }));
        Principal.add(fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void titul0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseClicked

    }//GEN-LAST:event_titul0MouseClicked

    private void titul0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseEntered

    }//GEN-LAST:event_titul0MouseEntered

    private void titul0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseExited

    }//GEN-LAST:event_titul0MouseExited

    private void esquerd_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esquerd_panelMouseEntered

    }//GEN-LAST:event_esquerd_panelMouseEntered

    private void enviar_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_imgActionPerformed
        JFileChooser choose= new JFileChooser();
        choose.setDialogTitle("Selecionar Imagem");
        choose.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagen","JPEG","png","jpg");

        choose.setFileFilter(filtro);

        int Return = choose.showOpenDialog(this);
        if(Return == JFileChooser.APPROVE_OPTION){
            File file = choose.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());

            imagem.setIcon(new javax.swing.ImageIcon(image.getImage().getScaledInstance(150,150, 150)));
            
       } 
    }//GEN-LAST:event_enviar_imgActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        this.limpar();
    }//GEN-LAST:event_limparActionPerformed

    private void PrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMouseEntered
        int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titul0.setVisible(false);}
    }//GEN-LAST:event_PrincipalMouseEntered

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed

            int position = part_2.getX();

            Animacion.Animacion.mover_derecha(position,0, 1, 50, part_2);
            proximo.setVisible(false);
            limpar.setVisible(false);

    }//GEN-LAST:event_proximoActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        if(Ano_carro.getText().isEmpty() || cor.getSelectedItem() == null || fabricante.getSelectedItem() == null
            || modelo.getText().isEmpty() || chassi.getText().isEmpty() || preco.getText().isEmpty()
            || quilometragem.getText().isEmpty() || descricao.getText().isEmpty()){
            //img
            
          JOptionPane.showMessageDialog(null, "Digite todos os campos!", "Vilet's Concessionária", JOptionPane.INFORMATION_MESSAGE);
            
        } else{
        
        VeiculoDAO dao = new VeiculoDAO();
        Veiculo vei = new Veiculo();
        
        vei.setAno(Ano_carro.getText());
        vei.setCor((String) cor.getSelectedItem());
        vei.setFabricante((String) fabricante.getSelectedItem());
        vei.setModelo(modelo.getText());
        vei.setNumChassi(chassi.getText());
        vei.setPreco(Integer.parseInt(preco.getText()));
        vei.setDescricao(descricao.getText());
        vei.setQuilometragem(Integer.valueOf(quilometragem.getText()));
        //img
        //adicionais
        dao.cadastrarVeiculo(vei);
        
            }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        int position = part_2.getX();

        Animacion.Animacion.mover_izquierda(position,-680, 1, 50, part_2);
        proximo.setVisible(true);
        limpar.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void part_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_part_2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_part_2MouseEntered

    private void chassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chassiActionPerformed

    private void arquent_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquent_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquent_checkActionPerformed

    private void cambio_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambio_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambio_checkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ano_carro;
    private javax.swing.JLabel N_chassi_text;
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel ano_text;
    private javax.swing.JCheckBox arcond_check;
    private javax.swing.JCheckBox arquent_check;
    private javax.swing.JButton cadastrar;
    private javax.swing.JCheckBox cambio_check;
    private javax.swing.JTextField chassi;
    private javax.swing.JComboBox<String> cor;
    private javax.swing.JLabel cor_text;
    private javax.swing.JLabel desc_text;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton enviar_img;
    private javax.swing.JPanel esquerd_panel;
    private javax.swing.JLabel fabr_text;
    private javax.swing.JComboBox<String> fabricante;
    private javax.swing.JCheckBox gps_check;
    private javax.swing.JLabel imagem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField modelo;
    private javax.swing.JLabel modelo_text;
    private javax.swing.JLabel opcionais_text;
    private javax.swing.JPanel part_2;
    private javax.swing.JTextField preco;
    private javax.swing.JLabel preco_text;
    private javax.swing.JButton proximo;
    private javax.swing.JTextField quilometragem;
    private javax.swing.JLabel quilometragem_text;
    private javax.swing.JCheckBox radio_check;
    private javax.swing.JCheckBox tetosolar_check;
    private javax.swing.JLabel titul0;
    private javax.swing.JCheckBox trava_check;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
public void bordas(){
            org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
            dropShadowBorder2.setShadowColor(new java.awt.Color(0,0,0));
            dropShadowBorder2.setShadowOpacity(1.0F);
            dropShadowBorder2.setShadowSize(5);
            descricao.setBorder(dropShadowBorder2);

}

}
