package view.Gerente;

import dao.GerenteDAO;
import dao.VeiculoDAO;
import java.io.File;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Veiculo;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Tabela_veiculo extends javax.swing.JPanel {

    public Tabela_veiculo() {
        initComponents();
        Veiculo_tabela();
    }
    public void Veiculo_tabela(){
    DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
    model.setNumRows(0);
    GerenteDAO dao = new GerenteDAO();
    
    for(Veiculo v: dao.ListarVeiculos()){
        model.addRow(new Object[]{
            v.getId(),
            v.getFoto(),   
            v.getModelo(),
            v.getFabricante(),
            v.getAno(),
            v.getCor(),
            v.getPreco(),
            v.getNumChassi(),
            v.getDescricao(),
            v.getQuilometragem()
        });
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tools = new javax.swing.JPopupMenu();
        Apagar = new javax.swing.JMenuItem();
        Ver_relatorio = new javax.swing.JMenuItem();
        rpdf = new javax.swing.JMenuItem();
        Alterar = new javax.swing.JMenuItem();
        Principal = new javax.swing.JPanel();
        Part2 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        alterar_btn = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();
        enviar_img = new javax.swing.JButton();
        modelo = new javax.swing.JTextField();
        modelo_text = new javax.swing.JLabel();
        fabricante = new javax.swing.JComboBox<>();
        fabr_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        desc_text = new javax.swing.JLabel();
        quilometragem = new javax.swing.JTextField();
        Qulimetragem_text = new javax.swing.JLabel();
        cor_text = new javax.swing.JLabel();
        Ano_carro = new javax.swing.JFormattedTextField();
        Ano_text = new javax.swing.JLabel();
        chassi = new javax.swing.JTextField();
        N_chassi_text = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        cor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cambio_check = new javax.swing.JCheckBox();
        trava_check = new javax.swing.JCheckBox();
        arquent_check = new javax.swing.JCheckBox();
        tetosolar_check = new javax.swing.JCheckBox();
        radio_check = new javax.swing.JCheckBox();
        arcond_check = new javax.swing.JCheckBox();
        gps_check = new javax.swing.JCheckBox();
        Qulimetragem_text1 = new javax.swing.JLabel();
        esquerd_panel = new javax.swing.JPanel();
        titul0 = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        Tabela_scroll = new javax.swing.JScrollPane();
        Tabela = new rojerusan.RSTableMetro();
        atualizar = new javax.swing.JButton();

        Tools.setBackground(new java.awt.Color(255, 255, 255));
        Tools.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tools.setForeground(new java.awt.Color(0, 255, 255));
        Tools.setOpaque(false);

        Apagar.setBackground(new java.awt.Color(255, 255, 255));
        Apagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Apagar.setForeground(new java.awt.Color(0, 255, 255));
        Apagar.setText("Apagar");
        Apagar.setContentAreaFilled(false);
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });
        Tools.add(Apagar);

        Ver_relatorio.setBackground(new java.awt.Color(255, 255, 255));
        Ver_relatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ver_relatorio.setForeground(new java.awt.Color(0, 255, 255));
        Ver_relatorio.setText("Exibir relatório");
        Ver_relatorio.setContentAreaFilled(false);
        Ver_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_relatorioActionPerformed(evt);
            }
        });
        Tools.add(Ver_relatorio);

        rpdf.setBackground(new java.awt.Color(255, 255, 255));
        rpdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rpdf.setForeground(new java.awt.Color(0, 255, 255));
        rpdf.setText("Relatório em PDF");
        rpdf.setContentAreaFilled(false);
        rpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpdfActionPerformed(evt);
            }
        });
        Tools.add(rpdf);

        Alterar.setBackground(new java.awt.Color(255, 255, 255));
        Alterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alterar.setForeground(new java.awt.Color(0, 255, 255));
        Alterar.setText("Alterar dados");
        Alterar.setContentAreaFilled(false);
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        Tools.add(Alterar);

        Principal.setBackground(new java.awt.Color(0, 0, 0));
        Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrincipalMouseEntered(evt);
            }
        });
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Part2.setBackground(new java.awt.Color(0, 0, 0));
        Part2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part2MouseEntered(evt);
            }
        });
        Part2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setBackground(new java.awt.Color(0, 255, 255));
        voltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.setOpaque(true);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        Part2.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 120, 40));

        alterar_btn.setBackground(new java.awt.Color(0, 255, 255));
        alterar_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterar_btn.setForeground(new java.awt.Color(255, 255, 255));
        alterar_btn.setText("Alterar");
        alterar_btn.setBorder(null);
        alterar_btn.setContentAreaFilled(false);
        alterar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alterar_btn.setOpaque(true);
        alterar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_btnActionPerformed(evt);
            }
        });
        Part2.add(alterar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 120, 40));

        imagem.setBackground(new java.awt.Color(255, 255, 255));
        imagem.setForeground(new java.awt.Color(255, 255, 255));
        imagem.setOpaque(true);
        Part2.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 150, 150));

        enviar_img.setBackground(new java.awt.Color(0, 255, 255));
        enviar_img.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enviar_img.setForeground(new java.awt.Color(255, 255, 255));
        enviar_img.setText("Selecionar imagem");
        enviar_img.setBorder(null);
        enviar_img.setBorderPainted(false);
        enviar_img.setContentAreaFilled(false);
        enviar_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar_img.setOpaque(true);
        enviar_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_imgActionPerformed(evt);
            }
        });
        Part2.add(enviar_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 180, 40));

        modelo.setBackground(new java.awt.Color(0, 255, 255));
        modelo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        modelo.setForeground(new java.awt.Color(255, 0, 0));
        modelo.setToolTipText("Insira o modelo do carro");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder1.setShadowOpacity(1.0F);
        dropShadowBorder1.setShadowSize(10);
        modelo.setBorder(dropShadowBorder1);
        modelo.setCaretColor(new java.awt.Color(255, 0, 0));
        modelo.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        modelo.setOpaque(false);
        Part2.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 246, 51));

        modelo_text.setBackground(new java.awt.Color(0, 255, 255));
        modelo_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        modelo_text.setForeground(new java.awt.Color(255, 255, 255));
        modelo_text.setText("Modelo:");
        Part2.add(modelo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        fabricante.setBackground(new java.awt.Color(0, 0, 0));
        fabricante.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fabricante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hyundai", "Peugeot", "Toyota", "Chevrolet", "Ford", "Nissan", "Volkswagen", "Honda", "Mercedes-Benz", "Renault", "Suzuki", "Mitsubishi", " " }));
        fabricante.setBorder(null);
        fabricante.setOpaque(false);
        Part2.add(fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        fabr_text.setBackground(new java.awt.Color(255, 255, 255));
        fabr_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        fabr_text.setForeground(new java.awt.Color(255, 255, 255));
        fabr_text.setText("Fabricante:");
        Part2.add(fabr_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        descricao.setColumns(20);
        descricao.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 0, 0));
        descricao.setRows(5);
        descricao.setToolTipText("Descreva o carro");
        jScrollPane1.setViewportView(descricao);

        Part2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 220, -1));

        desc_text.setBackground(new java.awt.Color(255, 255, 255));
        desc_text.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        desc_text.setForeground(new java.awt.Color(255, 255, 255));
        desc_text.setText("Descrição:");
        Part2.add(desc_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        quilometragem.setBackground(new java.awt.Color(0, 255, 255));
        quilometragem.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        quilometragem.setForeground(new java.awt.Color(255, 0, 0));
        quilometragem.setToolTipText("Insira a quilometragem do carro");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder2.setShadowOpacity(1.0F);
        dropShadowBorder2.setShadowSize(10);
        quilometragem.setBorder(dropShadowBorder2);
        quilometragem.setCaretColor(new java.awt.Color(255, 0, 0));
        quilometragem.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        quilometragem.setOpaque(false);
        Part2.add(quilometragem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 140, 51));

        Qulimetragem_text.setBackground(new java.awt.Color(0, 255, 255));
        Qulimetragem_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Qulimetragem_text.setForeground(new java.awt.Color(255, 255, 255));
        Qulimetragem_text.setText("Preço:");
        Part2.add(Qulimetragem_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        cor_text.setBackground(new java.awt.Color(0, 255, 255));
        cor_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        cor_text.setForeground(new java.awt.Color(255, 255, 255));
        cor_text.setText("Cor:");
        Part2.add(cor_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Ano_carro.setBackground(new java.awt.Color(0, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder3.setShadowOpacity(1.0F);
        dropShadowBorder3.setShadowSize(10);
        Ano_carro.setBorder(dropShadowBorder3);
        Ano_carro.setForeground(new java.awt.Color(255, 0, 0));
        try {
            Ano_carro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Ano_carro.setToolTipText("Insira o ano do carro");
        Ano_carro.setCaretColor(new java.awt.Color(255, 0, 0));
        Ano_carro.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        Ano_carro.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Ano_carro.setOpaque(false);
        Part2.add(Ano_carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 51));

        Ano_text.setBackground(new java.awt.Color(0, 255, 255));
        Ano_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Ano_text.setForeground(new java.awt.Color(255, 255, 255));
        Ano_text.setText("Ano:");
        Part2.add(Ano_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        chassi.setBackground(new java.awt.Color(0, 255, 255));
        chassi.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        chassi.setForeground(new java.awt.Color(255, 0, 0));
        chassi.setToolTipText("Insira o N° do chassi");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder4.setShadowOpacity(1.0F);
        dropShadowBorder4.setShadowSize(10);
        chassi.setBorder(dropShadowBorder4);
        chassi.setCaretColor(new java.awt.Color(255, 0, 0));
        chassi.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        chassi.setOpaque(false);
        chassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chassiActionPerformed(evt);
            }
        });
        Part2.add(chassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 246, 51));

        N_chassi_text.setBackground(new java.awt.Color(0, 255, 255));
        N_chassi_text.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        N_chassi_text.setForeground(new java.awt.Color(255, 255, 255));
        N_chassi_text.setText("Numero do Chassi:");
        Part2.add(N_chassi_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        preco.setBackground(new java.awt.Color(0, 255, 255));
        preco.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        preco.setForeground(new java.awt.Color(255, 0, 0));
        preco.setToolTipText("Insira o preço do carro");
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShadowColor(new java.awt.Color(0, 255, 255));
        dropShadowBorder5.setShadowOpacity(1.0F);
        dropShadowBorder5.setShadowSize(10);
        preco.setBorder(dropShadowBorder5);
        preco.setCaretColor(new java.awt.Color(255, 0, 0));
        preco.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        preco.setOpaque(false);
        preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoActionPerformed(evt);
            }
        });
        Part2.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 51));

        cor.setBackground(new java.awt.Color(0, 0, 0));
        cor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preto", "Cinza", "Azul", "Vermelho", "Prata", "Amarelo", "Rosa" }));
        cor.setBorder(null);
        cor.setOpaque(false);
        Part2.add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 90, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Opcionais");
        Part2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        cambio_check.setForeground(new java.awt.Color(255, 255, 255));
        cambio_check.setText("Câmbio Automático");
        cambio_check.setBorder(null);
        cambio_check.setOpaque(false);
        cambio_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambio_checkActionPerformed(evt);
            }
        });
        Part2.add(cambio_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        trava_check.setForeground(new java.awt.Color(255, 255, 255));
        trava_check.setText("Trava elétrica");
        trava_check.setBorder(null);
        trava_check.setOpaque(false);
        Part2.add(trava_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        arquent_check.setForeground(new java.awt.Color(255, 255, 255));
        arquent_check.setText("Ar quente");
        arquent_check.setBorder(null);
        arquent_check.setOpaque(false);
        arquent_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquent_checkActionPerformed(evt);
            }
        });
        Part2.add(arquent_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        tetosolar_check.setForeground(new java.awt.Color(255, 255, 255));
        tetosolar_check.setText("Teto Solar");
        tetosolar_check.setBorder(null);
        tetosolar_check.setOpaque(false);
        Part2.add(tetosolar_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        radio_check.setForeground(new java.awt.Color(255, 255, 255));
        radio_check.setText("Rádio");
        radio_check.setBorder(null);
        radio_check.setOpaque(false);
        Part2.add(radio_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        arcond_check.setForeground(new java.awt.Color(255, 255, 255));
        arcond_check.setText("Ar condicionado");
        arcond_check.setBorder(null);
        arcond_check.setOpaque(false);
        Part2.add(arcond_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        gps_check.setForeground(new java.awt.Color(255, 255, 255));
        gps_check.setText("GPS");
        gps_check.setBorder(null);
        gps_check.setOpaque(false);
        Part2.add(gps_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        Qulimetragem_text1.setBackground(new java.awt.Color(0, 255, 255));
        Qulimetragem_text1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Qulimetragem_text1.setForeground(new java.awt.Color(255, 255, 255));
        Qulimetragem_text1.setText("Quilometragem:");
        Part2.add(Qulimetragem_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        Principal.add(Part2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-750, 0, 700, 600));

        esquerd_panel.setBackground(new java.awt.Color(0, 255, 255));
        esquerd_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                esquerd_panelMouseEntered(evt);
            }
        });

        titul0.setBackground(new java.awt.Color(0, 0, 0));
        titul0.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        titul0.setForeground(new java.awt.Color(255, 255, 255));
        titul0.setText("Veiculos Registrados");
        titul0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titul0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titul0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                titul0MouseExited(evt);
            }
        });

        javax.swing.GroupLayout esquerd_panelLayout = new javax.swing.GroupLayout(esquerd_panel);
        esquerd_panel.setLayout(esquerd_panelLayout);
        esquerd_panelLayout.setHorizontalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esquerd_panelLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(titul0)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        esquerd_panelLayout.setVerticalGroup(
            esquerd_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esquerd_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titul0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Principal.add(esquerd_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        limpar.setBackground(new java.awt.Color(0, 255, 255));
        limpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.setBorder(null);
        limpar.setContentAreaFilled(false);
        limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpar.setOpaque(true);
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        Principal.add(limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 120, 30));

        Tabela_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Tabela_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Tabela_scroll.setPreferredSize(new java.awt.Dimension(620, 300));

        Tabela.setBackground(new java.awt.Color(0, 0, 0));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Imagem", "Modelo", "Fabricante", "Ano", "Cor", "Preço", "Nº Chassi", "Descrição", "Quilometragem"
            }
        ));
        Tabela.setColorBackgoundHead(new java.awt.Color(0, 255, 255));
        Tabela.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabela.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabela.setColorSelBackgound(new java.awt.Color(0, 255, 255));
        Tabela.setComponentPopupMenu(Tools);
        Tabela.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        Tabela.setFuenteFilas(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Tabela.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tabela.setGridColor(new java.awt.Color(230, 230, 230));
        Tabela.setOpaque(false);
        Tabela.setRowHeight(20);
        Tabela.setRowMargin(0);
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela_scroll.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setResizable(false);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
            Tabela.getColumnModel().getColumn(4).setResizable(false);
            Tabela.getColumnModel().getColumn(5).setResizable(false);
            Tabela.getColumnModel().getColumn(6).setResizable(false);
            Tabela.getColumnModel().getColumn(7).setResizable(false);
            Tabela.getColumnModel().getColumn(8).setResizable(false);
            Tabela.getColumnModel().getColumn(9).setResizable(false);
        }

        Principal.add(Tabela_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 620, 300));

        atualizar.setBackground(new java.awt.Color(0, 255, 255));
        atualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        atualizar.setForeground(new java.awt.Color(255, 255, 255));
        atualizar.setText("Atualizar");
        atualizar.setBorder(null);
        atualizar.setContentAreaFilled(false);
        atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizar.setOpaque(true);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        Principal.add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titul0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseClicked

    }//GEN-LAST:event_titul0MouseClicked

    private void titul0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseEntered

    }//GEN-LAST:event_titul0MouseEntered

    private void titul0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titul0MouseExited

    }//GEN-LAST:event_titul0MouseExited

    private void esquerd_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esquerd_panelMouseEntered

    }//GEN-LAST:event_esquerd_panelMouseEntered

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        //limpar oq? '-'
    }//GEN-LAST:event_limparActionPerformed

    private void PrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMouseEntered
        int position = esquerd_panel.getY();
        Animacion.Animacion.subir(position,-60, 1, 5, esquerd_panel);
        if(position != 0){
            esquerd_panel.setVisible(false);
            titul0.setVisible(false);}
    }//GEN-LAST:event_PrincipalMouseEntered

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
        VeiculoDAO dao = new VeiculoDAO();
        Veiculo vv = new Veiculo();
        
      if(Tabela.getSelectedRow() == -1){
           JOptionPane.showMessageDialog(null, "Selecione uma linha", " Vilet's Muscles Informa...", JOptionPane.ERROR_MESSAGE); 
      } else{
         int id = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 1);
         vv.setId(id);
         dao.excluirVeiculo(vv);
      }
    }//GEN-LAST:event_ApagarActionPerformed

    private void Ver_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_relatorioActionPerformed
        Connection conn= connection.ConnectionFactory.getConnection();

        String src="./src/Relatorio_modelo/relatorio.jasper";

        JasperPrint jasperPrint= null;
        try {
            jasperPrint= JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
        JasperViewer view= new JasperViewer(jasperPrint,false);
        view.setVisible(true);
    }//GEN-LAST:event_Ver_relatorioActionPerformed

    private void rpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpdfActionPerformed
        Connection conn= connection.ConnectionFactory.getConnection();
        try {
            JasperReport jasperReport= JasperCompileManager.compileReport("./src/Relatorio_modelo/relatorio.jrxml");

            JasperPrint jasperPrint= JasperFillManager.fillReport(jasperReport, null,conn);
            Date data= new Date();
            SimpleDateFormat form= new SimpleDateFormat("ddMMyyy");

            JasperExportManager.exportReportToPdfFile(jasperPrint,"./Relatorios/"+form.format(data)+".pdf");

        } catch (JRException ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_rpdfActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        int position = Part2.getX();
        Animacion.Animacion.mover_derecha(position,Part2.getWidth()*0, 1, 50, Part2);
        atualizar.setVisible(false);
        limpar.setVisible(false);
        Tabela.setVisible(false);
        setarCampos(modelo, chassi, quilometragem, descricao, preco, Ano_carro, Tabela, cor);
        
        
    }//GEN-LAST:event_AlterarActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        setarCampos(modelo, chassi, quilometragem, descricao, preco, Ano_carro, Tabela, cor);
        JOptionPane.showMessageDialog(this, "Tabela Atualizada!", " Vilet's Muscles Informa...", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_atualizarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        int position = Part2.getX();

        Animacion.Animacion.mover_izquierda(position,Part2.getWidth()*-1, 1, 50, Part2);
        atualizar.setVisible(true);
        limpar.setVisible(true);
        Tabela.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void alterar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_btnActionPerformed

    }//GEN-LAST:event_alterar_btnActionPerformed

    private void Part2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Part2MouseEntered

    private void enviar_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_imgActionPerformed
        JFileChooser choose= new JFileChooser();
        choose.setDialogTitle("Selecionar Imagem");
        choose.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagen","JPEG","png","jpg");

        choose.setFileFilter(filtro);

        int Return = choose.showOpenDialog(this);
        if(Return == JFileChooser.APPROVE_OPTION){
            File file = choose.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());

            imagem.setIcon(new javax.swing.ImageIcon(image.getImage().getScaledInstance(150,150, 150)));

        }
    }//GEN-LAST:event_enviar_imgActionPerformed

    private void chassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chassiActionPerformed

    private void cambio_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambio_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambio_checkActionPerformed

    private void arquent_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquent_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquent_checkActionPerformed

    private void precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alterar;
    private javax.swing.JFormattedTextField Ano_carro;
    private javax.swing.JLabel Ano_text;
    private javax.swing.JMenuItem Apagar;
    private javax.swing.JLabel N_chassi_text;
    private javax.swing.JPanel Part2;
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel Qulimetragem_text;
    private javax.swing.JLabel Qulimetragem_text1;
    private rojerusan.RSTableMetro Tabela;
    private javax.swing.JScrollPane Tabela_scroll;
    private javax.swing.JPopupMenu Tools;
    private javax.swing.JMenuItem Ver_relatorio;
    private javax.swing.JButton alterar_btn;
    private javax.swing.JCheckBox arcond_check;
    private javax.swing.JCheckBox arquent_check;
    private javax.swing.JButton atualizar;
    private javax.swing.JCheckBox cambio_check;
    private javax.swing.JTextField chassi;
    private javax.swing.JComboBox<String> cor;
    private javax.swing.JLabel cor_text;
    private javax.swing.JLabel desc_text;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton enviar_img;
    private javax.swing.JPanel esquerd_panel;
    private javax.swing.JLabel fabr_text;
    private javax.swing.JComboBox<String> fabricante;
    private javax.swing.JCheckBox gps_check;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField modelo;
    private javax.swing.JLabel modelo_text;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField quilometragem;
    private javax.swing.JCheckBox radio_check;
    private javax.swing.JMenuItem rpdf;
    private javax.swing.JCheckBox tetosolar_check;
    private javax.swing.JLabel titul0;
    private javax.swing.JCheckBox trava_check;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
 
JCheckBox[] box = {radio_check, arcond_check, arquent_check, cambio_check, tetosolar_check, trava_check, gps_check};

 public void setarCampos(JTextField modelo,
         JTextField chassi, 
         JTextField quilometragem,
         JTextArea descricao, 
         JTextField preco,
         JFormattedTextField ano,
         JTable Tabela,
         JComboBox jj
 ){
 
       modelo.setText(this.Tabela.getValueAt(this.Tabela.getSelectedRow(), 2).toString());
       jj.setSelectedItem(this.Tabela.getValueAt(this.Tabela.getSelectedRow(),3).toString());
       ano.setText(this.Tabela.getValueAt(this.Tabela.getSelectedRow(), 4).toString());
       preco.setText(this.Tabela.getValueAt(this.Tabela.getSelectedRow(), 6).toString());   
       chassi.setText(this.Tabela.getValueAt(this.Tabela.getSelectedRow(), 7).toString());
       descricao.setText(this.Tabela.getValueAt(this.Tabela.getSelectedRow(), 8).toString());
       quilometragem.setText(this.Tabela.getValueAt(this.Tabela.getSelectedRow(), 9).toString());
      
 }
}


 




